name: Compilar APK con Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git python3-pip \
          libffi-dev libssl-dev cmake gettext ffmpeg zlib1g-dev \
          libjpeg-dev libpng-dev \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Buildozer y Cython
      run: |
        pip install --upgrade pip
        pip install "cython<3.0.0" buildozer

    - name: Compilar APK
      env:
        # Anular los NDKs del sistema runner
        ANDROID_NDK_HOME: ''
        ANDROID_NDK_ROOT: ''
        ANDROID_NDK: ''
      run: |
        buildozer -v android debug

    - name: Subir Artefacto APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
