name: Compilar APK con Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar dependencias del sistema y librerías C/C++
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          python3-pip \
          libffi-dev \
          libssl-dev \
          cmake \
          gettext \
          ffmpeg \
          zlib1g-dev \
          libjpeg-dev \
          libpng-dev \
          libfreetype6-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          zip \
          unzip

    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Buildozer y Cython compatible
      run: |
        pip install --upgrade pip
        pip install "cython==0.29.36" buildozer

    - name: Limpiar build anterior y compilar APK
      env:
        ANDROID_NDK_HOME: ''
        ANDROID_NDK_ROOT: ''
        ANDROID_NDK: ''
      run: |
     
        buildozer -v android debug

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
